# Generated by Django 5.0.2 on 2024-03-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
